chat/urls.py
from django.urls import path
from . import views

app_name = "chat"
urlpatterns = [
    path('', views.home, name='home'),
    # path('home/', views.main, name='main'),
    path('post/', views.post, name='post'),
    path('messages/', views.messages, name='messages'),
    path('upload/', views.upload, name='views.upload'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('chat.urls', namespace="chat")),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

chat/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Chat(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=255)
    user = models.ForeignKey(User, related_name="messages" ,on_delete=models.CASCADE)

    def __str__(self):
        return self.message

class Contact(models.Model):
    name = models.CharField(blank=True,null=True ,max_length=50)
    subject = models.CharField(blank=True, null=True,max_length=10)
    mail = models.EmailField(blank=True, null=True,max_length=254)
    message = models.CharField(blank=True, null=True,max_length=500)

chat/views.py
import os
from chat.models import Chat
import speech_recognition as sr
from django.http import HttpResponse
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from chat.models import Contact


def home(request):
    chats = Chat.objects.all()
    all_users = User.objects.filter(messages__isnull=False).distinct()
    ctx = {
        'home': 'active',
        'chat': chats,
        'allusers': all_users
    }
    if request.user.is_authenticated:
        return render(request, 'chat.html', ctx)
    else:
        if request.method == 'POST':
            name = request.POST['name']
            subject = request.POST['subject']
            mail = request.POST['mail']
            message = request.POST['message']
            contact = Contact(name=name, mail=mail,subject=subject, message=message)
            contact.save()
        # return render(request, 'base.html', None)
        return render(request, 'index.html', None)
       
# def main(request):
#     if request.method == 'POST':
#         name = request.POST['name']
#         subject = request.POST['subject']
#         mail = request.POST['mail']
#         message = request.POST['message']
#         contact = Contact(name=name, mail=mail,subject=subject, message=message)
#         contact.save()
#             # return render(request,'doctor/index.html')
#         return render(request, 'index.html', None)
#     return render(request, 'index.html', None)


def upload(request):
    customHeader = request.META['HTTP_MYCUSTOMHEADER']

    # obviously handle correct naming of the file and place it somewhere like media/uploads/
    filename = str(Chat.objects.count())
    filename = filename + "name" + ".wav"
    uploadedFile = open(filename, "wb")
    # the actual file is in request.body
    uploadedFile.write(request.body)
    uploadedFile.close()
    # put additional logic like creating a model instance or something like this here
    r = sr.Recognizer()
    harvard = sr.AudioFile(filename)
    with harvard as source:
        audio = r.record(source)
    msg = r.recognize_google(audio)
    os.remove(filename)
    chat_message = Chat(user=request.user, message=msg)
    if msg != '':
        chat_message.save()
    return redirect('/')


def post(request):
    if request.method == "POST":
        msg = request.POST.get('msgbox', None)
        print('Our value = ', msg)
        chat_message = Chat(user=request.user, message=msg)
        if msg != '':
            chat_message.save()
        return JsonResponse({'msg': msg, 'user': chat_message.user.username})
    else:
        return HttpResponse('Request should be POST.')


def messages(request):
    chat = Chat.objects.all()
    return render(request, 'messages.html', {'chat': chat})

templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load account %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat</title>

{#    < Chat js >#}
    <title>WebRTC Audio Recording using MediaStreamRecorder</title>

    <script src="https://cdn.WebRTC-Experiment.com/MediaStreamRecorder.js"></script>
    <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>

{#    <link rel="stylesheet" href="https://cdn.webrtc-experiment.com/style.css">#}


    {% include "head_css.html" %}
    {% block extra_css %}{% endblock %}
    {% block extra_js %}{% endblock %}

{#    < Chat js>#}
        <style>
        input {
            border: 1px solid rgb(255, 255, 255);
            border-radius: 3px;
            font-size: 1em;
            outline: none;
            padding: .2em .4em;
            width: 60px;
            text-align: center;
        }
        select {
            vertical-align: middle;
            line-height: 1;
            padding: 2px 5px;
            height: auto;
            font-size: inherit;
            margin: 0;
        }
    </style>

</head>
<body style="background: rgb(255, 255, 255)">
{% block navbar %}
    <nav class="navbar navbar-default" style="background: rgb(0, 0, 0); border-color:rgb(17, 17, 17)">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"Chat</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li ><a href="/" style="color: white; font-size: 18px">KIIAA</a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_anonymous %}
                        <a href="/accounts/login/">
                            <button type="button" class="btn navbar-btn btn-success">Sign in</button>
                        </a>
                        <a href="/accounts/signup/">
                            <button type="button" class="btn navbar-btn btn-success">Register</button>
                        </a>
                    {% else %}
                        <a href="/accounts/logout/">
                            <button style="background-color: #f5bc4e; color: white; border: #f5bc4e; border-radius: 2px;" type="button" class="btn btn-danger navbar-btn">Log out</button>
                        </a>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
{% endblock navbar %}



{% block content %}
    <header class="body-header">
        <div class="body-header__title">
            <h1 class="text-center">Speech To text live chat</h1>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <p class="lead text-center">Please Login! to the website</p>
        </div>
    </div>
{% endblock %}



 {% include "chat_script.html" %}
<script src="{% static 'chat/js/jquery-1.12.3.js' %}"></script>
<script src="{% static 'chat/js/bootstrap.min.js' %}"></script>
<script src="{% static 'chat/js/script.js' %}"></script>
</body>
</html>

templates/chat.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-2" style="margin-left: 20px; padding: 10px ; border: solid rgb(0, 0, 0)">
        <div class="container" >
        {% if user.is_authenticated %}
            <p style="color: black; font-size: 18px">
                    Username: <b style="color: #f5bc4e;">{{ user.username }}</b>
            </p>
            <p style="color: black; font-size: 18px">
                    Total Messages:  <b style="color: #f5bc4e;">{{ chat|length }}</b>
            </p>

            <br>

            <h5 style="color: black; font-size: 18px; width: 200px;">
                Users who participated in chat:
            </h5>

            {% for obj in allusers %}
                <p>
                    User Name:  <b style="color: #f5bc4e;">{{ obj.username }}</b>
                </p>
            {% endfor %}

        {% endif %}
        </div>
      </div>
        <div class="col-lg-8">
        <div class="container">
            <div id="chat-body" class="panel panel-default">
                <div class="panel-heading" style="color: #f5bc4e; background: black">Speech to text Chat Box</div>
                <div id="msg-list-div" class="panel-body">
                    <ul id="msg-list" class="list-group">
                        {% for obj in chat %}
                            <b>{{ obj.user }}</b>
                            {% if obj.user == request.user %}
                                <li class="text-right list-group-item">{{ obj.message }}</li>
                            {% else %}
                                <li class="text-left list-group-item">{{ obj.message }}</li>
                            {% endif %}
                        {% empty %}
                            <li class="text-right list-group-item">No messages yet!</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <br>

            <h3> Send Message </h3>

            <form id="chat-form" method="post" action="{% url 'chat:post' %}" >
                {% csrf_token %}
                <div id="chat-bottom" class="input-group">
    {#                <input type="text" style="border: solid rgb(0, 0, 0)" id="chat-msg" name="chat-msg" class="form-control"/>#}
                    <textarea id="chat-msg" name="chat-msg" class="form-control" />
                    </textarea>
                    <span class="input-group-btn">
                    <input class="btn btn-default" id="send" type="submit" style="color: rgb(0, 0, 0); padding: 16px" value="Send"/>
                </span>
                </div>
            </form>

            <article>
            <header style="text-align: center;">


            </header>

            <section class="experiment" >

                <br>
                <h3>
                    Send Message: Speech to text
                </h3>
                <button style="background-color: #f5bc4e; color: white; border: #f5bc4e; border-radius: 1px;" id="start-recording">Start</button>
                <button style="background-color: #f5bc4e; color: white; border: #f5bc4e; border-radius: 1px;" id="stop-recording" disabled>Stop</button>

                <button style="background-color: #f5bc4e; color: white; border: #f5bc4e; border-radius: 1px;" id="pause-recording" disabled>Pause</button>
                <button style="background-color: #f5bc4e; color: white; border: #f5bc4e; border-radius: 1px;" id="resume-recording" disabled>Resume</button>

            </section>

            <section class="experiment">
                <div id="audios-container"></div>
            </section>

        </article>

        </div>
        </div>
    </div>
{% endblock content %}

templates/chat_script.html
<script>
            function captureUserMedia(mediaConstraints, successCallback, errorCallback) {
                navigator.mediaDevices.getUserMedia(mediaConstraints).then(successCallback).catch(errorCallback);
            }

            var mediaConstraints = {
                audio: true
            };

            document.querySelector('#start-recording').onclick = function() {
                this.disabled = true;
                captureUserMedia(mediaConstraints, onMediaSuccess, onMediaError);
            };

            document.querySelector('#stop-recording').onclick = function() {
                this.disabled = true;
                mediaRecorder.stop();
                mediaRecorder.stream.stop();

                while (audiosContainer.firstChild) {
                    audiosContainer.removeChild(audiosContainer.firstChild);
                }

                document.querySelector('#pause-recording').disabled = true;
                document.querySelector('#start-recording').disabled = false;
            };

            document.querySelector('#pause-recording').onclick = function() {
                this.disabled = true;
                mediaRecorder.pause();

                document.querySelector('#resume-recording').disabled = false;
            };

            document.querySelector('#resume-recording').onclick = function() {
                this.disabled = true;
                mediaRecorder.resume();

                document.querySelector('#pause-recording').disabled = false;
            };

            {#document.querySelector('#save-recording').onclick = function() {#}
            {#    this.disabled = true;#}
            {#    mediaRecorder.save();#}
            {##}
            {#    // alert('Drop WebM file on Chrome or Firefox. Both can play entire file. VLC player or other players may not work.');#}
            {#};#}

            var mediaRecorder;

            function onMediaSuccess(stream) {
                var audio = document.createElement('audio');

                audio = mergeProps(audio, {
                    controls: true,
                    muted: true
                });
                audio.srcObject = stream;
                audio.play();

                audiosContainer.appendChild(audio);
                audiosContainer.appendChild(document.createElement('hr'));

                mediaRecorder = new MediaStreamRecorder(stream);
                mediaRecorder.stream = stream;


                mediaRecorder.recorderType = StereoAudioRecorder;
                mediaRecorder.mimeType = 'audio/wav';


                // don't force any mimeType; use above "recorderType" instead.
                // mediaRecorder.mimeType = 'audio/webm'; // audio/ogg or audio/wav or audio/webm

                mediaRecorder.audioChannels = true;
                mediaRecorder.ondataavailable = function(blob) {
                    var a = document.createElement('a');
                    a.target = '_blank';
                    a.innerHTML = 'Open Recorded Audio No. ' + (index++) + ' (Size: ' + bytesToSize(blob.size) + ') Time Length: ' + getTimeLength(timeInterval);

                    a.href = URL.createObjectURL(blob);

                    {#audiosContainer.appendChild(a);#}
                    {#audiosContainer.appendChild(document.createElement('hr'));#}

                     function getCookie(name) {
                            var cookieValue = null;
                            if (document.cookie && document.cookie != '') {
                                var cookies = document.cookie.split(';');
                                for (var i = 0; i < cookies.length; i++) {
                                    var cookie = jQuery.trim(cookies[i]);
                                    // Does this cookie string begin with the name we want?
                                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                        break;
                                    }
                                }
                            }
                            return cookieValue;
                        }

                        var csrftoken = getCookie('csrftoken');
                        var xhr = new XMLHttpRequest();
                        xhr.open('POST', 'upload/', true);
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        xhr.setRequestHeader("MyCustomHeader", "Put anything you need in here, like an ID");
                        xhr.send(blob);
                };

                var timeInterval = 10000;
                if (timeInterval) timeInterval = parseInt(timeInterval);
                else timeInterval = 5 * 1000;

                // get blob after specific time interval
                mediaRecorder.start(timeInterval);

                document.querySelector('#stop-recording').disabled = false;
                document.querySelector('#pause-recording').disabled = false;
                document.querySelector('#save-recording').disabled = false;
            }

            function onMediaError(e) {
                console.error('media error', e);
            }

            var audiosContainer = document.getElementById('audios-container');
            var index = 1;

            // below function via: http://goo.gl/B3ae8c
            function bytesToSize(bytes) {
                var k = 1000;
                var sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
                if (bytes === 0) return '0 Bytes';
                var i = parseInt(Math.floor(Math.log(bytes) / Math.log(k)), 10);
                return (bytes / Math.pow(k, i)).toPrecision(3) + ' ' + sizes[i];
            }

            // below function via: http://goo.gl/6QNDcI
            function getTimeLength(milliseconds) {
                var data = new Date(milliseconds);
                return data.getUTCHours() + " hours, " + data.getUTCMinutes() + " minutes and " + data.getUTCSeconds() + " second(s)";
            }

            window.onbeforeunload = function() {
                document.querySelector('#start-recording').disabled = false;
            };
        </script>

<section class="experiment"><small id="send-message"></small></section>

<script>
    window.useThisGithubPath = 'streamproc/MediaStreamRecorder';
</script>
<script src="https://cdn.webrtc-experiment.com/commits.js" async></script>

templates/head_css.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'chat/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'chat/css/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker3.min.css">

templates/messages.html
{% for obj in chat %}
<br/>
    {% if obj.user == request.user %}
        <b>{{ obj.user }}:</b><li class="text-right list-group-item">{{ obj.message }}</li>
    {% else %}
        <b>{{ obj.user }}:</b><li class="text-left list-group-item">{{ obj.message }}</li>
    {% endif %}
{% empty %}
    <li class="text-right list-group-item">No messages yet!</li>
{% endfor %}